### PR TITLE
Walkscore

### PR DESCRIPTION
**Pull request by dreuss**
Add a widget that shows a walkscore badge / walkscore for current location.  Based on a Client URN / Location URN that goes to g5-hub.herokuapp.com, and grabs the proper address / lat / long for a **Location** , then hops over to the g5-social-feed-service to make a request to the Walkscore API to get the walkscore for the location, and serve it back to the widget with some nice styles.  Quite the mouthful to output an image / span tag on screen.

### CODE REVIEW

**Comment by ceckert** [comment]
@dreuss I assume the requirements didn't specifically call out configuration options for the widget, but is there any way to get the Client URN and Location URN from the CMS, rather than requiring it to be configured by a web builder? I would like to start making out widgets more user-friendly, and not requiring configuration for values that should be inferred from the CMS and location the widget is added to would help. Please discuss with Garrett and decide if this story should be extended with these requirements, or if a new story is needed to remove the config options.

**Comment by dreuss** [comment]
@ceckert agreed, manual input of these fields for configuration is redundant.  We might want to check in with @johnlucia as he is working on 'making the widgets' smarter initiative, so I'll touch base with him.

**Comment by johnlucia** [comment]
@ceckert as of right now, there's no way for a widget to reach up and grab that kind of information from it's parent location. Problem is our hot mess of nested widgets, where child widgets inside a column inside a row have no idea what web template, drop target, or location they belong to. I'm working on some changes to the CMS right now that will allow that. I have it working, but so far it's full on hackery. So, in another couple days I should have something marginally useful on that front.

**Comment by ceckert** [comment]
@johnlucia @variousred and I worked with @bbauer on a solution for this, a way to get the parent widget for a widget, using a DB query for settings and the widget id in the case when the widget does not have a drop target set (i.e children widgets of layout widgets). You should be able to get the website for a widget without any changes to the CMS, just some SQL trickery. Chat with MJ, or let me know if I should dig up that code.

**Comment by johnlucia** [comment]
:+1: 

Talked with @ceckert a bit, and sounds like the rodeo SQL he's talking about could be useful for the Smarter Widgets effort, but we still have the problem of the widget garden being really, really extraordinarily dumb, and having no access to the Ruby code he mentions.

I'm still chipping away at a few problems with assigning parent/child associations in new and existing widgets, so it might be a while until we have what you need to get rid of those fields. Also, there's a good chance we'll end up leaving a some of these redundant fields in place in case there's some reason to override the standard defaults. 

So, I'd say let 'er rip.

**Pull request merged**
